#测试配置
spring:
   datasource:
      url: jdbc:mysql://192.168.65.40:3306/coca
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: false
   jackson:
     date-format: yyyy-MM-dd HH:mm:ss