#开发配置
spring:
  datasource:
    continue-on-error: true
    url: jdbc:mysql://127.0.0.1:3306/public_resource
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 10
    maxActive: 25
    max-idle: 20
    min-idel: 10
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    show-sql: true
---
spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    port: 6379
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
      max-wait: -1
---
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: wangkan
    password: wangkan
    publisher-confirms: true
---
fileTransfer:
    root: d:\download
    temp: d:\tmp
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 10Mb
      max-request-size: 50Mb
server:
  tomcat:
    uri-encoding: UTF-8
---
spring:
  messages:
    basename: messages_provider
---
logging:
  config: classpath:logback-spring.xml
  file: publicResource
  path: D:/logs